# Profile information
name: doriri
title: Doriri Blog
description: 소비자의 관점, 소비자 중심으로 생각하는 웹 개발자입니다.
baseurl: "/doriri" # the subpath of your site, e.g. /blog
url: "https://minhyeong-jang.github.io" # the base hostname & protocol for your site, e.g. http://example.com
image: 

facebook:
  app_id: 481301675773678

# Folder Link
asset_url: /assets
image_url: /assets/images
font_url: /assets/fonts

# Social
github: https://github.com/minhyeong-jang

# Contact form
email: public.doriri@gmail.com

# Comments
discus-identifier: # Add your Disqus identifier

# Paginate
paginate: 5
paginate_path: '/categories/:num'


permalink: /:year/:month/:day/:title


collections:
  authors:
    output: true
    permalink: /authors/:path/
  tags:
    output: true
    permalink: /tags/:path/
  categories:
    output: true
    permalink: /categories/:path/

defaults:
  - scope:
      path: ''
      type: authors
    values:
      layout: author
  - scope:
      path: ''
      type: tags
    values:
      layout: category
  - scope:
      path: ''
      type: categories
    values:
      layout: category

      
# Build settings
# markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages, _]
sass:
  style: compressed
  sass_dir: assets/css